FROM python:3.10

WORKDIR /code

## dependency of pyresparser
USER root
RUN apt update
RUN apt -y install build-essential 
RUN apt-get update
RUN apt-get -y install python3-dev
RUN pip install nltk
RUN pip install -U pip setuptools wheel
RUN pip install spacy
RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
RUN pip install pyresparser
RUN python -m spacy download en_core_web_sm
RUN python -m spacy validate
RUN python -m nltk.downloader words
RUN python -m nltk.downloader stopwords

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]